---
tenants:
  MY_FABRIC:
    vrfs:
      default:
        svis:
          30:
            name: 'Thirty'
            tags: [ "30" ]
            enabled: true
            ip_virtual_router_addresses:
              - 10.30.30.1
            nodes:
              s2-spine1:
                ip_address: 10.30.30.2/24
              s2-spine2:
                ip_address: 10.30.30.3/24
          40:
            name: 'Forty'
            tags: [ "40" ]
            enabled: true
            ip_virtual_router_addresses:
              - 10.40.40.1
            nodes:
              s2-spine1:
                ip_address: 10.40.40.2/24
              s2-spine2:
                ip_address: 10.40.40.3/24
          45:
            name: 'Forty-five'
            tags: [ "45" ]
            enabled: true
            ip_virtual_router_addresses:
              - 10.45.45.1
            nodes:
              s2-spine1:
                ip_address: 10.45.45.2/24
              s2-spine2:
                ip_address: 10.45.45.3/24

##################################################################
# WAN/Core Edge Links
##################################################################

core_interfaces:
  p2p_links:

    - ip: [ 10.0.0.37/31, 10.0.0.36/31 ]
      nodes: [ s2-spine1, WANCORE ]
      interfaces: [ Ethernet7, Ethernet2 ]
      include_in_underlay_protocol: true

    - ip: [ 10.0.0.41/31, 10.0.0.40/31 ]
      nodes: [ s2-spine1, WANCORE ]
      interfaces: [ Ethernet8, Ethernet2 ]
      include_in_underlay_protocol: true

    - ip: [ 10.0.0.39/31, 10.0.0.38/31 ]
      nodes: [ s2-spine2, WANCORE ]
      interfaces: [ Ethernet7, Ethernet2 ]
      include_in_underlay_protocol: true

    - ip: [ 10.0.0.43/31, 10.0.0.42/31 ]
      nodes: [ s2-spine2, WANCORE ]
      interfaces: [ Ethernet8, Ethernet2 ]
      include_in_underlay_protocol: true
